name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: output
          filename: github-metrics.svg
          
          # Options
          user: ritikthakur22
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6
          
          # Lines of code plugin
          plugin_lines: yes
          
          # Habits plugin
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
